# Generated by Django 2.2.25 on 2021-12-17 13:35
from __future__ import absolute_import, division, print_function

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gargoyle', '0002_bytes_to_str'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='switch',
                    name='value',
                    field=jsonfield.fields.JSONField(default=dict),
                ),
            ],
            database_operations=[],
        )
    ]
