[tox]
envlist =
    py{37}-codestyle,
    py{37}-django{22,32}

[testenv]
setenv =
    PYTHONDONTWRITEBYTECODE=1
deps =
    django18: Django>=1.8,<1.9
    django19: Django>=1.9,<1.10
    django22: Django>=2.2,<3.0
    django32: Django>=3.2,<4.0
    -rrequirements.txt
commands = ./runtests.py {posargs}


[testenv:py37-codestyle]
deps = -rrequirements.txt
commands = multilint
